module.exports = {
	disableEmoji: true,
	maxMessageLength: 64,
	minMessageLength: 3,
	closedIssueMessage: 'Ref: ',
	list: [
		'feat',
		'fix',
		'test',
		'chore',
		'docs',
		'refactor',
		'style',
		'ci',
		'perf',
	],
	questions: [
		'type',
		'subject',
		'body',
		'issues',
	],
	scopes: [],
	types: {
		chore: {
			description: 'Build process or auxiliary tool changes',
			value: 'chore',
			section: 'Build System',
			hidden: false,
		},
		ci: {
			description: 'CI related changes',
			value: 'ci',
			section: 'Build System',
			hidden: true,
		},
		docs: {
			description: 'Documentation only changes',
			value: 'docs',
			section: 'Documentation',
			hidden: false,
		},
		feat: {
			description: 'A new feature or change of functionality',
			value: 'feat',
			section: 'Features',
			hidden: false,
		},
		fix: {
			description: 'A bug fix',
			value: 'fix',
			section: 'Fixes',
			hidden: false,
		},
		perf: {
			description: 'A code change that improves performance',
			value: 'perf',
			section: 'Improvements',
			hidden: false,
		},
		refactor: {
			description: 'A code change that neither fixes a bug or adds a feature',
			value: 'refactor',
			section: 'Improvements',
			hidden: false,
		},
		release: {
			description: 'Create a release commit',
			value: 'release',
			section: 'Build System',
			hidden: true,
		},
		style: {
			description: 'Markup, white-space, formatting, missing semi-colons...',
			value: 'style',
			section: 'Improvements',
			hidden: true,
		},
		test: {
			description: 'Adding missing tests',
			value: 'test',
			section: 'Tests',
			hidden: false,
		},
	},
};
