name: 'Build & Test'

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: Manual triggered build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Bundle code
      run: npm run build
